name: Daily arXiv Summary to Slack

on:
  schedule:
    - cron: "45 16 * * *"   # UTC 16:45 = JST 01:45
  workflow_dispatch:

permissions:
  contents: read
  models: read

concurrency:
  group: daily-arxiv
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_MODELS_PAT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      GITHUB_ORG: ${{ secrets.GITHUB_ORG }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug: show repo tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort

      - name: Sanity check GitHub Models token
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then echo "GITHUB_TOKEN is EMPTY"; exit 1; fi
          export GITHUB_TOKEN="$(printf %s "$GITHUB_TOKEN" | tr -d '\r\n')"
          if [ -n "$GITHUB_ORG" ]; then
            URL="https://models.github.ai/orgs/${GITHUB_ORG}/catalog/models"
          else
            URL="https://models.github.ai/catalog/models"
          fi
          CODE=$(curl -s -o /tmp/models.json -w "%{http_code}" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" "$URL")
          echo "Catalog status: $CODE"
          if [ "$CODE" != "200" ]; then cat /tmp/models.json; exit 1; fi

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install arxiv requests slack_sdk
          fi

      - name: Run arXiv summary
        run: python src/arxiv_llm_slack.py
